use_frameworks!

project 'PopupKitExample.xcodeproj'

def popupkit
    pod 'PopupKit', :path => "../"
end

target 'PopupKit_ObjC_Example' do
    popupkit
    target 'PopupKit_ObjC_ExampleUITests' do
        popupkit
    end
end

target 'PopupKit_tvOS_Example' do
    popupkit
end

target 'PopupKit_Swift_Example' do
    popupkit
end
